config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/:user', to: 'videos#collection', as: :collection
  resources :users
  resources :videos, only: %i[new create show update destroy]
  get 'videos/edit/:url', to: 'videos#edit', as: :edit_video
  patch 'videos/views/:id', to: 'videos#increase_views'
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :photo, PhotoUploader

  has_many :videos, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, format: {
    with: /\A[\w|\s]+\z/,
    message: 'only allow letters and spaces'
  }
  validates :last_name, format: {
    with: /\A[\w|\s]+\z/,
    message: 'only allow letters and spaces'
  }
  validates :display_name,
            uniqueness: true,
            format: {
              with: /\A[\w|\-|\s|\u00C0-\u00FF]+\z/,
              message: "only allows letters, numbers, underscores, dashes and spaces"
            }
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  mount_uploader :miniature, PhotoUploader
  after_create :set_url

  validates :name, format: {
    with: /\A[\w|\-|\s|\u00C0-\u00FF]+\z/,
    message: "only allows letters, numbers, underscores, dashes and spaces"
  }
  validates :miniature, presence: true, on: :create

  private

  def set_url
    update(url: "#{id}-#{name.parameterize}.m3u8")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name display_name photo])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[display_name photo])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @videos = Video.all.order(:id).reverse
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[show destroy]
  skip_before_action :authenticate_user!, only: %i[show collection increase_views]

  def new
    @video = Video.new
    authorize @video
  end

  def create
    @video = Video.new(video_params)
    @video.user = current_user
    authorize @video
    if @video.save
      redirect_to video_path(@video.url), notice: 'Your video was successfully created!'
    else
      render :new
    end
  end

  def show; end

  def collection
    @user = User.find_by(display_name: params[:user])
    @videos = Video.where(user: @user)
    authorize @videos
  end

  def edit
    url = "#{params[:url]}.#{params[:format]}"
    @video = Video.find_by(url: url)
    authorize @video
  end

  def update
    @video = Video.find(params[:id])
    authorize @video
    if @video.update(video_params)
      @video.update_column(:url, "#{@video.id}-#{@video.name.parameterize}.m3u8")
      redirect_to video_path(@video.url), notice: 'Your video was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    authorize @video
    @video.destroy
    redirect_to root_path
  end

  def increase_views
    @video = Video.find(params[:id])
    authorize @video
    @views = @video.views + 1
    respond_to { |format| format.js } if @video.update(views: @views)
  end

  private

  def set_video
    url = "#{params[:id]}.#{params[:format]}"
    @video = Video.find_by(url: url)
    authorize @video
  end

  def video_params
    params.require(:video).permit(:name, :miniature)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Moovy</title>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
    <script src="https://unpkg.com/video.js/dist/video.js"></script>
    <%#script src="https://unpkg.com/videojs-flash/dist/videojs-flash.js"></script%>
    <%#script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script%>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= javascript_include_tag 'application' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('home-banner.jpg')  %>);">
  <div class="banner-content">
    <h1>Moovy is just the best video platform in the world</h1>
    <p>Create your own videos and get popular as you ever dreamed</p>
    <%= link_to "Create a video", new_video_path %>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="videos">
        <h1>Videos</h1>
      </div>
    </div>
  </div>
  <div class="video-cards">
    <div class="row">
      <% unless @videos.nil? %>
        <% @videos.each do |video| %>
        <div class="col-12 col-sm-6 col-md-3">
          <%= link_to video_path(video.url), class: 'video-card' do %>
            <%= cl_image_tag video.miniature, class: 'img-fluid' %>
            <div class="video-card-content">
              <%= video.name %>
            </div>
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="navbar-logo">
      <img class="img-fluid img-round" src="<%= image_path("logo.png") %>" alt="Logo">
      <h3>Moovy</h3>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i style="color: white;" class="fas fa-bars"></i>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Create a video", new_video_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user[:photo] == nil %>
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit my info", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/videos/collection.html.erb
<div class="collection-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('home-banner.jpg')  %>);">
  <div class="collection-banner-content">
    <% if @user[:photo] == nil %>
      <%= image_tag "avatar.png", class: "img-fluid" %>
    <% else %>
      <%= cl_image_tag @user.photo, class: 'img-fluid' %>
    <% end %>
    <h1><%= @user.display_name %></h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="videos">
        <h1><%= @user.display_name %>'s videos</h1>
      </div>
    </div>
  </div>
  <div class="video-cards">
    <div class="row">
      <% unless @videos.nil? %>
        <% @videos.each do |video| %>
        <div class="col-12 col-sm-6 col-md-3">
          <%= link_to video_path(video.url), class: 'video-card' do %>
            <%= cl_image_tag video.miniature, class: 'img-fluid' %>
            <div class="video-card-content">
              <%= video.name %>
            </div>
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/edit.html.erb
<body style="background: #f2f2f2;">
  <div class="container">
    <div class="row">
      <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
        <div class="form-container">
          <div class="form">
            <div class="form-title">
              <h2>Edit video</h2>
            </div>
            <div class="video-form">
              <%= simple_form_for(@video) do |f| %>
                <%= f.error_notification %>
                <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                <%= f.input :name %>
                <%= f.input :miniature %>
                <%= f.input :miniature_cache, as: :hidden %>
                <%= f.submit value: 'Update video', class: 'button button-dark' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/videos/increase_views.js.erb
$('#views')[0].innerHTML = `Views: ${<%= @views %>}`

app/views/videos/new.html.erb
<body style="background: #f2f2f2;">
  <div class="container">
    <div class="row">
      <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-4 offset-md-4">
        <div class="form-container">
          <div class="form">
            <div class="form-title">
              <h2>Create your video</h2>
            </div>
            <div class="video-form">
              <%= simple_form_for(@video) do |f| %>
                <%= f.error_notification %>
                <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                <%= f.input :name, required: true %>
                <%= f.input :miniature, required: true %>
                <%= f.input :miniature_cache, as: :hidden %>
                <%= f.submit value: 'Create video', class: 'button button-dark' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/videos/show.html.erb
<body style="background: #131418">
  <div class="container">
    <div class="row">
      <div class="col-10 offset-1 col-sm-12 offset-sm-0 col-md-10 offset-md-1" style="margin-top: 66px;">
        <div class="video-show">
          <h1 id="video-title" data-video="<%= @video.id %>"><%= @video.name %></h1>
          <video id="video" onplay="videoPlay()" class="video-js vjs-default-skin" controls autoplay>
            <source
            src="https://content.jwplatform.com/manifests/yp34SRmf.m3u8"
            type="application/x-mpegURL">
          </video>
          <div class="video-info">
            <%= link_to collection_path(@video.user.display_name) do %>
              <% if @video.user[:photo] == nil %>
                <%= image_tag "avatar.png", class: "img-fluid avatar" %>
              <% else %>
                <%= cl_image_tag @video.user.photo, class: 'img-fluid avatar' %>
              <% end %>
              <%= @video.user.display_name %>
            <% end %>
            <p id="views" >Views: <%= @video.views %></p>
            <% if current_user %>
              <% if policy(@video).destroy? %>
                <div class="video-owner">
                  <%= link_to "Edit video", edit_video_path(@video.url), class: 'button button-outline-white' %>
                  <%= link_to "Delete video", video_path(@video.url), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button button-outline-white' %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>